/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appjava.Forms;

import javax.swing.JOptionPane;

/**
 *
 * @author STUDENTS
 */
public class FormEx2 extends javax.swing.JFrame {

    /**
     * Creates new form FormEx2
     */
    public FormEx2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        PatientLabel = new javax.swing.JLabel();
        PatientField = new javax.swing.JTextField();
        BaseLabel = new javax.swing.JLabel();
        BaseField = new javax.swing.JTextField();
        WardLabel = new javax.swing.JLabel();
        WardField = new javax.swing.JTextField();
        LabLabel = new javax.swing.JLabel();
        LabField = new javax.swing.JTextField();
        GrossLabel = new javax.swing.JLabel();
        GrossField = new javax.swing.JTextField();
        InsLabel = new javax.swing.JLabel();
        InsField = new javax.swing.JTextField();
        VatLabel = new javax.swing.JLabel();
        VatField = new javax.swing.JTextField();
        OtherLabel = new javax.swing.JLabel();
        OtherField = new javax.swing.JTextField();
        NetLabel = new javax.swing.JLabel();
        NetField = new javax.swing.JTextField();
        CalcBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Patient Billing Form");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        TitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        TitleLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("HOSPITAL PATIENT BILLING FORM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleLabel)
                .addGap(94, 94, 94))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TitleLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PatientLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PatientLabel.setText("Patient Name:");

        BaseLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        BaseLabel.setText("Base Treatment Cost");

        WardLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        WardLabel.setText("Ward Charge (15%)");

        LabLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LabLabel.setText("Lab & Pharmacy (5%)");

        GrossLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        GrossLabel.setText("Gross Bill");

        InsLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        InsLabel.setText("Insurance (5%)");

        VatLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        VatLabel.setText("VAT");

        OtherLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        OtherLabel.setText("Other Deductions");

        NetLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NetLabel.setText("Net Payable");

        CalcBtn.setBackground(new java.awt.Color(0, 102, 102));
        CalcBtn.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        CalcBtn.setForeground(new java.awt.Color(204, 204, 204));
        CalcBtn.setText("Calculate");
        CalcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcBtnActionPerformed(evt);
            }
        });

        ClearBtn.setBackground(new java.awt.Color(255, 51, 51));
        ClearBtn.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        ClearBtn.setText("Clear");

        ExitBtn.setBackground(new java.awt.Color(204, 255, 255));
        ExitBtn.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PatientLabel)
                    .addComponent(BaseLabel)
                    .addComponent(WardLabel)
                    .addComponent(LabLabel)
                    .addComponent(GrossLabel)
                    .addComponent(InsLabel)
                    .addComponent(OtherLabel)
                    .addComponent(VatLabel)
                    .addComponent(NetLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CalcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NetField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OtherField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VatField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrossField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WardField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(PatientLabel)
                    .addComponent(PatientField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BaseLabel)
                    .addComponent(BaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(WardLabel)
                    .addComponent(WardField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LabLabel)
                    .addComponent(LabField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(GrossLabel)
                    .addComponent(GrossField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(InsLabel)
                    .addComponent(InsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(VatLabel)
                    .addComponent(VatField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(OtherLabel)
                    .addComponent(OtherField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(NetLabel)
                    .addComponent(NetField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void CalcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcBtnActionPerformed
        // TODO add your handling code here:
        try {         
            if (BaseField.getText().isEmpty() || OtherField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Fill all required!");
            } else {
                double baseCost = Double.parseDouble(BaseField.getText());
                double wardCost = baseCost * 0.15;
                double labCost = baseCost * 0.05;
                double grossBill = baseCost + wardCost + labCost;
                
                double insCost = grossBill * 0.05;
                double vatCost = grossBill * 0.18;
                double otherDedu = Double.parseDouble(OtherField.getText());
                double netPay = grossBill - insCost + vatCost - otherDedu;
                
                WardField.setText(String.format("%.2f", wardCost));
                LabField.setText(String.format("%.2f", labCost));
                GrossField.setText(String.format("%.2f", grossBill));
                InsField.setText(String.format("%.2f", insCost));
                VatField.setText(String.format("%.2f", vatCost));
                OtherField.setText(String.format("%.2f", otherDedu));
                NetField.setText(String.format("%.2f", netPay));
            }
            
        } catch (Exception e) {
            System.err.println("Could not calculate! " + e);
        }
    }//GEN-LAST:event_CalcBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEx2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEx2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEx2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEx2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEx2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BaseField;
    private javax.swing.JLabel BaseLabel;
    private javax.swing.JButton CalcBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JTextField GrossField;
    private javax.swing.JLabel GrossLabel;
    private javax.swing.JTextField InsField;
    private javax.swing.JLabel InsLabel;
    private javax.swing.JTextField LabField;
    private javax.swing.JLabel LabLabel;
    private javax.swing.JTextField NetField;
    private javax.swing.JLabel NetLabel;
    private javax.swing.JTextField OtherField;
    private javax.swing.JLabel OtherLabel;
    private javax.swing.JTextField PatientField;
    private javax.swing.JLabel PatientLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField VatField;
    private javax.swing.JLabel VatLabel;
    private javax.swing.JTextField WardField;
    private javax.swing.JLabel WardLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
