/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
DATABASE

CREATE DATABASE IF NOT EXISTS `test`;

USE test;

--
-- Table structure for table `student`
--

CREATE TABLE IF NOT EXISTS `student` (
  `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `Name` varchar(25) NOT NULL,
  `Age` int(11) NOT NULL,
  `Department` varchar(25) NOT NULL,
  `Gender` varchar(10) NOT NULL,
  `Nationality` varchar(25) NOT NULL,
  `Comments` text NOT NULL
);

*/
package appjava.Forms;

/**
 * Uok Student Feedback form
 * @author Danny Idukundatwese
 */

import java.sql.*;
import javax.swing.JOptionPane;

public class FormEx1 extends javax.swing.JFrame {
    
    public String ConnUrl;
    public Connection con;
    /**
     * Creates new form FormEx1
     */
    public FormEx1() {
        initComponents();
        GenderGrp.add(MaleRadio);
        GenderGrp.add(FemaleRadio);
        try {
            ConnUrl = "jdbc:mysql://localhost/test?" + "user=root&password=";
            con = DriverManager.getConnection(ConnUrl);
        }catch(SQLException e){
            System.out.println("Could not connect: " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGrp = new javax.swing.ButtonGroup();
        BackPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        AgeField = new javax.swing.JTextField();
        DepartField = new javax.swing.JTextField();
        DepartLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        MaleRadio = new javax.swing.JRadioButton();
        FemaleRadio = new javax.swing.JRadioButton();
        NationLabel = new javax.swing.JLabel();
        NationField = new javax.swing.JTextField();
        CommentLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentArea = new javax.swing.JTextArea();
        SubmitBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uok Students Form");
        setResizable(false);

        BackPanel.setBackground(new java.awt.Color(0, 153, 153));
        BackPanel.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        TitleLabel.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        TitleLabel.setText("Uok STUDENTS FORM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        NameLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NameLabel.setText("Name");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        AgeLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AgeLabel.setText("Age");

        AgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeFieldActionPerformed(evt);
            }
        });

        DepartField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartFieldActionPerformed(evt);
            }
        });

        DepartLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DepartLabel.setText("Department");

        GenderLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        GenderLabel.setText("Gender");

        MaleRadio.setText("Male");
        MaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioActionPerformed(evt);
            }
        });

        FemaleRadio.setText("Female");

        NationLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NationLabel.setText("Nationality");

        NationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationFieldActionPerformed(evt);
            }
        });

        CommentLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CommentLabel.setText("Comments");

        CommentArea.setColumns(20);
        CommentArea.setRows(5);
        jScrollPane1.setViewportView(CommentArea);

        SubmitBtn.setBackground(new java.awt.Color(0, 153, 102));
        SubmitBtn.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        SubmitBtn.setText("SUBMIT");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        DeleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        SaveBtn.setBackground(new java.awt.Color(0, 102, 204));
        SaveBtn.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        SaveBtn.setText("SAVE");

        javax.swing.GroupLayout BackPanelLayout = new javax.swing.GroupLayout(BackPanel);
        BackPanel.setLayout(BackPanelLayout);
        BackPanelLayout.setHorizontalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NationLabel)
                    .addComponent(GenderLabel)
                    .addComponent(DepartLabel)
                    .addComponent(AgeLabel)
                    .addComponent(NameLabel)
                    .addComponent(CommentLabel))
                .addGap(18, 18, 18)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackPanelLayout.createSequentialGroup()
                        .addComponent(MaleRadio)
                        .addGap(18, 18, 18)
                        .addComponent(FemaleRadio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackPanelLayout.createSequentialGroup()
                        .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BackPanelLayout.createSequentialGroup()
                                .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NationField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DepartField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackPanelLayout.createSequentialGroup()
                                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AgeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(76, 76, 76))))
        );
        BackPanelLayout.setVerticalGroup(
            BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartLabel)
                    .addComponent(DepartField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(MaleRadio)
                    .addComponent(FemaleRadio))
                .addGap(18, 18, 18)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NationLabel)
                    .addComponent(NationField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CommentLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(BackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void AgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeFieldActionPerformed

    private void DepartFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartFieldActionPerformed

    private void MaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRadioActionPerformed

    private void NationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationFieldActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:        
        try{
            String name = NameField.getText().trim();
            String age = AgeField.getText().trim();
            String depart = DepartField.getText().trim();
            String nation = NationField.getText().trim();
            String comm = CommentArea.getText().trim();
            String gender;
            
            if (name.isEmpty() || age.isEmpty() || depart.isEmpty() || nation.isEmpty() || comm.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Fill all required fields!");
                return;
            }
            
            if(MaleRadio.isSelected()) {
                gender = MaleRadio.getText().trim();
            } else {
                gender = FemaleRadio.getText().trim();
            }
                        
            PreparedStatement stmt = con.prepareStatement("INSERT INTO student(Name, Age, Department, Gender, Nationality, Comments) VALUES (?, ?, ?, ?, ?, ?)");
            stmt.setString(1, name);
            stmt.setString(2, age);
            stmt.setString(3, depart);
            stmt.setString(4, gender);
            stmt.setString(5, nation);
            stmt.setString(6, comm);
            
            int rowsAffected = stmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Successfully Added!");
            System.out.println(rowsAffected);
            
        }catch(SQLException e) {
            System.out.println("Could not insert: " + e.toString());
        }
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:        
        try {
            
            String nameDel = JOptionPane.showInputDialog("Name to Delete: ");
            
            PreparedStatement select_stmt = con.prepareStatement("SELECT * FROM student WHERE Name = ?");
            select_stmt.setString(1, nameDel);
            
            ResultSet rs = select_stmt.executeQuery();
            
            // Checking if the name already exist
            if (rs.next()) {                
                String idDel = Integer.toString(rs.getInt("id"));
                
                PreparedStatement stmt = con.prepareStatement("DELETE FROM student WHERE id = ?");
                stmt.setString(1, idDel);
                
                int rowsAffected = stmt.executeUpdate();
                
                if (rowsAffected > 0){
                    JOptionPane.showMessageDialog(this, "Deleted Successfully!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Student not found!");
            }
                        
        } catch (SQLException e) {
            System.out.println("Could not delete: " + e.toString());
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEx1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEx1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEx1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEx1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEx1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JPanel BackPanel;
    private javax.swing.JTextArea CommentArea;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField DepartField;
    private javax.swing.JLabel DepartLabel;
    private javax.swing.JRadioButton FemaleRadio;
    private javax.swing.ButtonGroup GenderGrp;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JRadioButton MaleRadio;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NationField;
    private javax.swing.JLabel NationLabel;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
